name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    name: Tests if the code builds successfully
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install Dependencies
        run: yarn install

      - name: Test Build
        run: yarn build
        
      - name: Test Serve
        run: yarn serve & sleep 10
    
      - name: Test curl
        run: |
            RESPONSE=$(curl -s -X GET http://localhost:3000)
            if echo "$RESPONSE" | grep -q "Skills Network Labs Knowledgebase"; then
              echo "Response contains expected text."
            else
              echo "Response does not contain expected text."
              exit 1
            fi
